"""Add ondelete='CASCADE' to city_id ForeignKey 

Revision ID: 684094f81939
Revises: 7597d504b9ab
Create Date: 2025-08-03 20:38:10.301227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684094f81939'
down_revision: Union[str, Sequence[str], None] = '7597d504b9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema for SQLite with CASCADE FK."""
    with op.batch_alter_table('temperatures', recreate="always") as batch_op:
        batch_op.create_foreign_key(
            constraint_name="fk_temperatures_city_id",
            referent_table="cities",
            local_cols=["city_id"],
            remote_cols=["id"],
            ondelete="CASCADE"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_temperatures_city_id", 'temperatures', type_='foreignkey')
    op.create_foreign_key(None, 'temperatures', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###
